[package]
name = "TurbosToken"
version = "0.0.1"
published-at = "0x97ba869857fd684dc888f48073887a3192de20a8c018e57fbf18971988069e9a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir="crates/sui-framework/packages/sui-framework/", rev = "devnet" }

[addresses]
turbos_token = "_"

[dev-addresses]
turbos_token = "0x0"